
import { Company } from './types';

export const COMPANIES: Company[] = [
    {
        id: 'fastclean',
        name: 'Dedetizadora FastClean',
        rating: 4.9,
        reviewsCount: 120,
        location: 'São Paulo - SP',
        shortLocation: 'São Paulo',
        description: 'Especialista em controle de pragas 24 horas.',
        tags: ['Residencial', '24 Horas', 'Licenciado'],
        specialties: ['Cupins', 'Ratos', 'Baratas'],
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDxQNfh6NONH3f917Twrugkmt_dO_NAAfSO7x6BhssUnszCrEa9So5_jVDAJTR1mk_Mz6t29rkTb8lhkQM8RdBK8_aJKhAfI-sdUQm1SZI23xHZdhLAFWqYWYo5kZItj1dJJb6EdnvT1rflzRZy8JqWlF_uCTPaLfOh-EmCaAOAb_VJ3Yl9lRTjYRVI92sDySPCMFGVMLKamhJjkJQWFXWj7XjB_J4LBaWBw8yIjAZFALgmQRaYaIvUDRFhxsCT_Z3zp1rUhZcMMMxo',
        isPremium: true,
        whatsapp: '(11) 99999-9999',
        status: 'APPROVED'
    },
    {
        id: 'jardim',
        name: 'Jardim Pragas Control',
        rating: 4.7,
        reviewsCount: 45,
        location: 'São Paulo - SP',
        shortLocation: 'São Paulo',
        description: 'Controle de pragas em jardins e áreas verdes.',
        tags: ['Comercial', 'Ratos'],
        specialties: ['Jardins', 'Roedores'],
        isPremium: false,
        whatsapp: '(11) 88888-8888',
        status: 'APPROVED'
    },
    {
        id: 'ecocontrol',
        name: 'EcoControl Soluções',
        rating: 4.5,
        reviewsCount: 28,
        location: 'São Paulo - SP',
        shortLocation: 'São Paulo',
        description: 'Soluções ecológicas para sua casa.',
        tags: ['Residencial', 'Cupins'],
        specialties: ['Cupins', 'Ecológico'],
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDyedzpoBRUjnkl8gBZ8uIuuP9xdIEDJpZ4FlxBc-WPpW9nCTOoyg9hmTR2bgxvsUPPJ9bjwO91G5bB2X0mhn0unnUc6l__Fd-BOVegRh3272xHqbsqB99eW8NVp1fDfgHcJnPpdPMSZqVN3G1vpUa6kukd5rmuc0KskTuV-RwlquKTg4FIASsbkZcQxriwNva89ivtEMIEAgx2ioFI8MTemJnC4dEIyk_tdWpeLMtml3OdXBZiSTgnKsRuWdru-12JoYmcJEWcxE9n',
        isPremium: false,
        whatsapp: '(11) 77777-7777',
        status: 'APPROVED'
    },
    {
        id: 'cesar-rj',
        name: 'César (RJ)',
        rating: 4.5,
        reviewsCount: 5,
        location: 'Rio de Janeiro - RJ',
        shortLocation: 'Rio de Janeiro',
        description: 'Atendimento personalizado no RJ.',
        tags: ['Residencial', 'Comercial'],
        specialties: ['Geral'],
        isPremium: false,
        whatsapp: '(21) 98346-2296',
        status: 'APPROVED'
    },
    {
        id: 'pragbot-participante',
        name: 'Participante PragBot',
        rating: 4.0,
        reviewsCount: 2,
        location: 'São Paulo - SP',
        shortLocation: 'São Paulo',
        description: 'Parceiro oficial PragBot.',
        tags: ['Residencial', 'Formigas'],
        specialties: ['Formigas'],
        isPremium: false,
        whatsapp: '(11) 97777-1234',
        status: 'APPROVED'
    },
    {
        id: 'gilmax-goiania',
        name: 'Gilmax Controle de Pragas',
        rating: 4.6,
        reviewsCount: 8,
        location: 'Goiânia - GO',
        shortLocation: 'Goiânia',
        description: 'Especialista em licitações e grandes áreas.',
        tags: ['Comercial', 'Licitações'],
        specialties: ['Grandes Áreas'],
        isPremium: false,
        whatsapp: '(62) 99852-6686',
        status: 'APPROVED'
    },
    {
        id: 'som-eduardo-jundiai',
        name: 'Som Eduardo Controle de Pragas',
        rating: 4.5,
        reviewsCount: 6,
        location: 'Jundiaí - SP',
        shortLocation: 'Jundiaí',
        description: 'Controle de cupins especializado.',
        tags: ['Residencial', 'Cupins'],
        specialties: ['Cupins'],
        isPremium: false,
        whatsapp: '(11) 97325-1927',
        status: 'APPROVED'
    },
    {
        id: 'renascer-assessoria-ambiental',
        name: 'RENASCER Assessoria Ambiental',
        rating: 4.9,
        reviewsCount: 12,
        location: 'Rio de Janeiro - RJ',
        shortLocation: 'Rio de Janeiro',
        description: 'Assessoria completa em saneamento.',
        tags: ['Condomínio', 'Sanitização'],
        specialties: ['Sanitização'],
        isPremium: true,
        whatsapp: '(21) 96437-3920',
        status: 'APPROVED'
    },
    {
        id: 'union-saneamento-ambiental',
        name: 'UniOn Saneamento Ambiental',
        rating: 4.5,
        reviewsCount: 7,
        location: 'Curitiba - PR',
        shortLocation: 'Curitiba',
        description: 'Controle integrado para indústrias.',
        tags: ['Industrial', 'Controle Integrado'],
        specialties: ['Industrial'],
        isPremium: false,
        whatsapp: '(41) 99988-7766',
        status: 'APPROVED'
    },
    {
        id: 'j-castro-eda',
        name: 'J Castro Eda',
        rating: 4.4,
        reviewsCount: 5,
        location: 'Fortaleza - CE',
        shortLocation: 'Fortaleza',
        description: 'Dedetização residencial eficiente.',
        tags: ['Residencial', 'Baratas'],
        specialties: ['Baratas'],
        isPremium: false,
        whatsapp: '(85) 99123-4567',
        status: 'APPROVED'
    },
    {
        id: 'insetbraz',
        name: 'Insetbraz',
        rating: 4.5,
        reviewsCount: 9,
        location: 'Belo Horizonte - MG',
        shortLocation: 'Belo Horizonte',
        description: 'Especialista em roedores.',
        tags: ['Comercial', 'Roedores'],
        specialties: ['Roedores'],
        isPremium: false,
        whatsapp: '(31) 98877-6655',
        status: 'APPROVED'
    },
    {
        id: 'doutor-dedetizacao',
        name: 'Doutor Dedetização',
        rating: 4.7,
        reviewsCount: 11,
        location: 'Porto Alegre - RS',
        shortLocation: 'Porto Alegre',
        description: 'Plantão 24h para emergências.',
        tags: ['Residencial', '24 Horas'],
        specialties: ['Emergências'],
        isPremium: true,
        whatsapp: '(51) 99911-2233',
        status: 'APPROVED'
    },
    {
        id: 'irmas-veneno',
        name: 'Irmas Veneno',
        rating: 4.6,
        reviewsCount: 10,
        location: 'Salvador - BA',
        shortLocation: 'Salvador',
        description: 'Cuidado especial com seu jardim.',
        tags: ['Residencial', 'Jardins'],
        specialties: ['Jardins'],
        isPremium: false,
        whatsapp: '(71) 98844-3322',
        status: 'APPROVED'
    },
    {
        id: 'lord-ambiental',
        name: 'Lord Ambiental',
        rating: 4.6,
        reviewsCount: 10,
        location: 'Manaus - AM',
        shortLocation: 'Manaus',
        description: 'Licenciamento e controle industrial.',
        tags: ['Industrial', 'Licenciado'],
        specialties: ['Industrial'],
        isPremium: false,
        whatsapp: '(92) 99122-3344',
        status: 'APPROVED'
    },
    {
        id: 'atipragas-controle-de-pragas',
        name: 'Atipragas Controle de Pragas',
        rating: 4.5,
        reviewsCount: 8,
        location: 'Recife - PE',
        shortLocation: 'Recife',
        description: 'Sanitização de ambientes.',
        tags: ['Condomínio', 'Sanitização'],
        specialties: ['Sanitização'],
        isPremium: false,
        whatsapp: '(81) 99655-4433',
        status: 'APPROVED'
    },
    {
        id: 'grupo-asca',
        name: 'Grupo Asca',
        rating: 4.4,
        reviewsCount: 6,
        location: 'Brasília - DF',
        shortLocation: 'Brasília',
        description: 'Atendendo governo e grandes empresas.',
        tags: ['Comercial', 'Governo'],
        specialties: ['Corporativo'],
        isPremium: false,
        whatsapp: '(61) 99877-6655',
        status: 'APPROVED'
    },
    {
        id: 'ac-controle-de-pragas',
        name: 'AC Controle de Pragas',
        rating: 4.5,
        reviewsCount: 9,
        location: 'Campinas - SP',
        shortLocation: 'Campinas',
        description: 'Controle de cupins em Campinas.',
        tags: ['Residencial', 'Cupins'],
        specialties: ['Cupins'],
        isPremium: false,
        whatsapp: '(19) 99123-9876',
        status: 'APPROVED'
    },
    {
        id: 'andre-luiz-passarelli',
        name: 'Andre Luiz Passarelli',
        rating: 4.3,
        reviewsCount: 3,
        location: 'Santos - SP',
        shortLocation: 'Santos',
        description: 'Dedetização no litoral.',
        tags: ['Residencial'],
        specialties: ['Geral'],
        isPremium: false,
        whatsapp: '(13) 99765-4321',
        status: 'APPROVED'
    },
    {
        id: 'licenciado-dedemax',
        name: 'Licenciado Dedemax',
        rating: 4.4,
        reviewsCount: 4,
        location: 'Ribeirão Preto - SP',
        shortLocation: 'Ribeirão Preto',
        description: 'Filial autorizada Dedemax.',
        tags: ['Residencial', 'Comercial'],
        specialties: ['Geral'],
        isPremium: false,
        whatsapp: '(16) 99234-5678',
        status: 'APPROVED'
    },
    {
        id: 'insetsantos',
        name: 'Insetsantos',
        rating: 4.5,
        reviewsCount: 7,
        location: 'Santos - SP',
        shortLocation: 'Santos',
        description: 'Especialista em condomínios no litoral.',
        tags: ['Condomínio', 'Litoral'],
        specialties: ['Condomínios'],
        isPremium: false,
        whatsapp: '(13) 98123-4567',
        status: 'APPROVED'
    },
    {
        id: 'controle-pragas-rio-preto',
        name: 'Controle de Pragas Rio Preto',
        rating: 5.0,
        reviewsCount: 15,
        location: 'São José do Rio Preto - SP',
        shortLocation: 'São José do Rio Preto',
        description: 'Atendimento especializado para clínicas.',
        tags: ['Condomínio', 'Clínica'],
        specialties: ['Saúde'],
        isPremium: true,
        whatsapp: '(17) 99660-9433',
        status: 'APPROVED'
    }
];
